### PR TITLE
Changed ZSO logic, now it will install zso only if original iso or bi…

### PR DESCRIPTION
**Pull request by AKuHAK**
…n is present in the same folder withthe same name

## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [ ] I checked to make sure my submission worked
- [ ] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK or other dependencies
- [ ] Others (please specify below)

### CODE REVIEW

**Comment by orcutt989** [comment]
Why did we do the iso/bin logic? This really screws it up for people trying to save space who keep local collections.

**Comment by AKuHAK** [comment]
You can extract zso before installation, and remove temporary iso after installation end. Otherwise opl and other utulities will be a bit buggy.

**Comment by synrais** [comment]
Zso on internal hdd seems pointless right now.
Just a really complicated way of getting iso onto an internal hdd now the logic has changed and the raw file size ends up the same or larger than iso on a ps2. There is no space saving or benefiet i can see so why is it even an option? 
Will using zso to save space on an internal hdd ever work or is there some technicality?

**Comment by orcutt989** [comment]
> Zso on internal hdd seems pointless right now. Just a really complicated way of getting iso onto an internal hdd now the logic has changed and the raw file size ends up the same or larger than iso on a ps2. There is no space saving or benefiet i can see so why is it even an option? Will using zso to save space on an internal hdd ever work or is there some technicality?

Can you elaborate on how raw file size is the same as a ZSO? ZSO provides a mechanism to highly compress images so you can fit more in the same space vs ISO.

**Comment by synrais** [comment]
1945 I II The Arcade Games.zso = 95mb
1945 I II The Arcade Games.iso = 161mb
Final game raw size on internal HDD = 256mb regardless of file used.

Found this whilst attempting to load around 1.4tb of ZSO to a 2tb drive and was full @1.3gb worth of ZSO. 
All raw sizes on internal HDD were the same as installing an ISO
ZSO space saving can only be done on a USB drive it seems.

**Pull request merged**
